language: ruby
bundler: cache
rvm:
- 2.2.1
script:
- bundle exec rake db:schema:load
- bundle exec rspec --color --format documentation
before_script:
- cp spec/dummy/config/database.example.yml config/database.yml
- cp spec/dummy/config/database.example.yml spec/dummy/config/database.yml
- mysql -e 'create database fagus_test;'
notifications:
  slack: wm-it:QEPmqezBb68PGS6a8OWwImYi
