language: ruby
addons:
  postgresql: '9.3'
bundler: cache
rvm:
- 2.2.1
script:
- bundle exec rake db:schema:load
- bundle exec rspec --color --format documentation
before_script:
- cp spec/dummy/config/database.example.yml config/database.yml
- cp spec/dummy/config/database.example.yml spec/dummy/config/database.yml
- psql -c 'create database fagus_test;' -U postgres
notifications:
  slack: wm-it:QEPmqezBb68PGS6a8OWwImYi
